In [141]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [142]:
!pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.6/dist-packages (0.8.1)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.1.2)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from geopandas) (2.6.1.post1)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from geopandas) (1.8.17)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.23.0->geopandas) (1.18.5)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (0.5.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (7.1.2)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.15.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (20.2.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas) (1.1.1)

In [143]:
!pip install pickle5
import pickle5 as pickle

Requirement already satisfied: pickle5 in /usr/local/lib/python3.6/dist-packages (0.0.11)

In [144]:
import pandas as pd
import numpy as np

import seaborn as sns
import warnings
warnings.filterwarnings(action='ignore')
import matplotlib.pyplot as plt
import geopandas as gpd

## 행정동별 개선 인프라 지수

In [312]:
with open('/content/drive/My Drive/수요지수_최종1012 (2).pkl', 'rb') as f:  
  suyo = pickle.load(f)

화곡제1동 / 독산제1동 / 광장동 각각 키움센터 하나씩 더해줌

정원도 서울특별시 센터별 정원수 더해줌

In [313]:
suyo.columns

Index(['행정동코드', '행정동', '0514세', '시군구명', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '키움센터_개수', '초등돌봄교실_이용인원', '초등돌봄교실_교실개수', '지역아동센터_정원', '지역아동센터_개수',
       '방과후아카데미_정원', '방과후아카데미_개수', '총시설수', 'tfidf', '돌봄교실이용비율', 'tfidf*이용비율',
       '행정동별0514세/전체0514세', 'tfidf*이용비율*인구비율', '정원 및 이용비율',
       'tfidf*정원 및 이용비율*인구비율', '예술학원', '보습학원개수', '총학원수', '학원tfidf', '총정원',
       '정원 및 이용비율(fix)', '수요지수', '수요지수_mmscaler', 'percentile'],
      dtype='object')

In [ ]:
cnt = 0
for i in range(len(suyo['총시설수'])):
    if suyo['총시설수'][i] != 0:
        cnt += 1
cnt

In [314]:
tf4 = [(max(suyo['총시설수']+1)-(float(suyo['총시설수'][i]))) for i in range(len(win))]
idf4 = np.log(len(suyo.행정동.unique()) / (1+cnt))
tfidf4 = [x*idf2 for x in tf4]
suyo['max센터tfidf'] = tfidf4
suyo['new수요지수'] = suyo['정원 및 이용비율(fix)'] * suyo['행정동별0514세/전체0514세'] *suyo['max센터tfidf']/suyo['학원tfidf']

In [316]:
pt = np.percentile(suyo[['new수요지수']],[i*10 for i in range(1,10)]).tolist()
len(pt)
# df2[df2['percentile'] == '10']
suyo['100분위'] = 0
suyo.loc[(suyo['new수요지수'] <= pt[0]),'100분위'] = '1'
suyo.loc[(suyo['new수요지수'] > pt[0]) & (suyo['new수요지수'] <= pt[1]),'100분위'] = '2'
suyo.loc[(suyo['new수요지수'] > pt[1]) & (suyo['new수요지수'] <= pt[2]),'100분위'] = '3'
suyo.loc[(suyo['new수요지수'] > pt[2]) & (suyo['new수요지수'] <= pt[3]),'100분위'] = '4'
suyo.loc[(suyo['new수요지수'] > pt[3]) & (suyo['new수요지수'] <= pt[4]),'100분위'] = '5'
suyo.loc[(suyo['new수요지수'] > pt[4]) & (suyo['new수요지수'] <= pt[5]),'100분위'] = '6'
suyo.loc[(suyo['new수요지수'] > pt[5]) & (suyo['new수요지수'] <= pt[6]),'100분위'] = '7'
suyo.loc[(suyo['new수요지수'] > pt[6]) & (suyo['new수요지수'] <= pt[7]),'100분위'] = '8'
suyo.loc[(suyo['new수요지수'] > pt[7]) & (suyo['new수요지수'] <= pt[8]),'100분위'] = '9'
suyo.loc[(suyo['new수요지수'] > pt[8]),'100분위'] = '10'

In [321]:
suyo.sort_values(by='new수요지수',ascending=False)
suyo.columns
df_last = suyo[['행정동코드', '행정동', '0514세', '시군구명', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '키움센터_개수', '초등돌봄교실_이용인원', '초등돌봄교실_교실개수', '지역아동센터_정원', '지역아동센터_개수',
       '방과후아카데미_정원', '방과후아카데미_개수', '총시설수', '돌봄교실이용비율', 'tfidf*이용비율',
       '행정동별0514세/전체0514세','예술학원', '보습학원개수', '총학원수', '학원tfidf', '총정원',
       '정원 및 이용비율(fix)', 'max센터tfidf','new수요지수', '100분위']]

In [324]:
df_last.sort_values(by='new수요지수',ascending=False)
df_last.to_pickle('1014수정_인프라지수.pickle')

In [222]:
win = suyo[['행정동코드', '행정동', '0514세', '시군구명', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '키움센터_개수', '초등돌봄교실_이용인원', '초등돌봄교실_교실개수', '지역아동센터_정원', '지역아동센터_개수',
       '방과후아카데미_정원', '방과후아카데미_개수', '총시설수','행정동별0514세/전체0514세','예술학원', '보습학원개수', '총학원수', '학원tfidf', '총정원',
       '정원 및 이용비율(fix)', '수요지수','percentile']]

In [223]:
cnt = 0
for i in range(len(suyo['총시설수'])):
    if suyo['총시설수'][i] != 0:
        cnt += 1
cnt

400

In [266]:
tf = [(max(win['총시설수']+1)-(float(win['총시설수'][i])))/2 for i in range(len(suyo))]
idf = np.log(len(win.행정동.unique()) / (1+cnt))
tfidf = [x*idf for x in tf]
win['센터tfidf'] = tfidf

In [267]:
win['re수요지수'] = win['정원 및 이용비율(fix)'] * win['행정동별0514세/전체0514세'] *win['센터tfidf']/win['학원tfidf']

In [268]:
pt = np.percentile(win[['re수요지수']],[i*10 for i in range(1,10)]).tolist()
len(pt)
# df2[df2['percentile'] == '10']
win['percentile_'] = 0
win.loc[(win['re수요지수'] <= pt[0]),'percentile_'] = '1'
win.loc[(win['re수요지수'] > pt[0]) & (win['re수요지수'] <= pt[1]),'percentile_'] = '2'
win.loc[(win['re수요지수'] > pt[1]) & (win['re수요지수'] <= pt[2]),'percentile_'] = '3'
win.loc[(win['re수요지수'] > pt[2]) & (win['re수요지수'] <= pt[3]),'percentile_'] = '4'
win.loc[(win['re수요지수'] > pt[3]) & (win['re수요지수'] <= pt[4]),'percentile_'] = '5'
win.loc[(win['re수요지수'] > pt[4]) & (win['re수요지수'] <= pt[5]),'percentile_'] = '6'
win.loc[(win['re수요지수'] > pt[5]) & (win['re수요지수'] <= pt[6]),'percentile_'] = '7'
win.loc[(win['re수요지수'] > pt[6]) & (win['re수요지수'] <= pt[7]),'percentile_'] = '8'
win.loc[(win['re수요지수'] > pt[7]) & (win['re수요지수'] <= pt[8]),'percentile_'] = '9'
win.loc[(win['re수요지수'] > pt[8]),'percentile_'] = '10'

In [269]:
win[win['시군구명']=='금천구']

          행정동코드    행정동  0514세 시군구명  ...  개선된돌봄교실이용비율  new센터tfidf  last수요지수  perc_
8    1154561000  독산제1동   2721  금천구  ...     0.007933    0.534108  0.000149      6
14   1154571000  시흥제5동   1131  금천구  ...     0.006783    1.175037  0.000218      9
20   1154567000  시흥제1동   2116  금천구  ...     0.004681    1.388680  0.000166      7
37   1154562000  독산제2동   1085  금천구  ...     0.004993    1.281858  0.000202      8
72   1154563000  독산제3동   1182  금천구  ...     0.004007    1.602323  0.000220      9
167  1154569000  시흥제3동    645  금천구  ...     0.002480    2.029609  0.000269      9
196  1154570000  시흥제4동   1404  금천구  ...     0.001133    2.456895  0.000099      4
205  1154564000  독산제4동    820  금천구  ...     0.001938    2.243252  0.000115      4
285  1154551000    가산동    627  금천구  ...     0.000558    2.563716  0.000037      2
311  1154568000  시흥제2동   2091  금천구  ...     0.002102    1.922787  0.000158      6

[10 rows x 34 columns]

In [270]:
win[['행정동','시군구명','총시설수','수요지수','re수요지수','총학원수']].sort_values(by='re수요지수',ascending=False).head(10)

        행정동 시군구명  총시설수      수요지수    re수요지수  총학원수
324     오륜동  송파구   4.0  0.000061  0.000129   8.0
25     월계3동  노원구  12.0  0.000249  0.000125  17.0
309    가락1동  송파구   6.0  0.000091  0.000124  10.0
316     내곡동  서초구   7.0  0.000109  0.000123  12.0
97    도봉제1동  도봉구  10.0  0.000179  0.000122   7.0
19     일원본동  강남구  11.0  0.000205  0.000120  24.0
41   신대방제2동  동작구  12.0  0.000234  0.000117  14.0
18     신월3동  양천구  11.0  0.000195  0.000114  11.0
290     번2동  강북구   1.0  0.000019  0.000112   0.0
127     중림동   중구   6.0  0.000082  0.000111   5.0

In [271]:
update = ['화곡제1동' , '독산제1동', '광장동']
up = []
for i in range(len(win)):
  if win['행정동'][i] in update:
    up.append(1)
  else:up.append(0)

ppl=[]
for i in range(len(suyo)):
  if win['행정동'][i] in update:
    ppl.append(28)   # 28명으로 반영(서울시 돌봄키움센터정원)
  else:ppl.append(0)
win['추가센터'],win['추가인원'] = up,ppl
win.columns

Index(['행정동코드', '행정동', '0514세', '시군구명', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '키움센터_개수', '초등돌봄교실_이용인원', '초등돌봄교실_교실개수', '지역아동센터_정원', '지역아동센터_개수',
       '방과후아카데미_정원', '방과후아카데미_개수', '총시설수', '행정동별0514세/전체0514세', '예술학원',
       '보습학원개수', '총학원수', '학원tfidf', '총정원', '정원 및 이용비율(fix)', '수요지수',
       'percentile', '센터tfidf', 're수요지수', 'percentile_', '추가센터', '추가인원',
       'new총정원', 'new총시설수', '개선된돌봄교실이용비율', 'new센터tfidf', 'last수요지수', 'perc_'],
      dtype='object')

추가정원 및 센터개수 반영

In [272]:
win['new총정원'] = win['총정원'] +win['추가인원']
win['new총시설수'] = win['총시설수'] +win['추가센터']
# win['new키움정원'] = win['키움센터_상시돌봄정원']+suyo['키움센터_일시돌봄정원'] +suyo['추가인원']
# win['new키움시설수'] = win['키움센터_개수'] +suyo['추가센터']

서울시 키움센터의 정원수를 반영

In [273]:
# 28명으로 반영
(sum(suyo['키움센터_상시돌봄정원'])+sum(suyo['키움센터_일시돌봄정원']))/sum(suyo['키움센터_개수'])

28.65934065934066

In [274]:
sum(win['new총정원']) == (sum(win['총정원']) + 28*3)
# suyo['개선된돌봄교실이용비율'] = [(x+1)/(sum(suyo['new총정원']) for x in suyo['new총정원']]
win['개선된돌봄교실이용비율'] = [(x+1)/sum(win['new총정원']) for x in win['new총정원']]

In [275]:
# cnt = 0
# for i in range(len(suyo['총시설수'])):
#     if suyo['총시설수'][i] != 0:
#         cnt += 1
# cnt

In [276]:
# cnt_new = 0
# for i in range(len(suyo['new총시설수'])):
#     if suyo['new총시설수'][i] != 0:
#         cnt_new += 1
# cnt_new

In [292]:
# max(suyo['총시설수']),(max(suyo['new총시설수']))

In [278]:
win

          행정동코드    행정동  0514세 시군구명  ...  개선된돌봄교실이용비율  new센터tfidf      last수요지수  perc_
0    1165065100   양재1동   5145  서초구  ...     0.009657    0.106822  5.815786e-05      2
1    1153078000  오류제2동   4507  구로구  ...     0.007506    0.534108  1.477873e-04      6
2    1150063000  방화제1동   4970  강서구  ...     0.006373    0.961394  1.964761e-04      8
3    1138069000    진관동   7384  은평구  ...     0.008343    0.213643  1.175963e-04      5
4    1138062500    역촌동   3381  은평구  ...     0.005108    1.495501  2.083160e-04      8
..          ...    ...    ...  ...  ...          ...         ...           ...    ...
419  1114057000     필동    180   중구  ...     0.000016    2.670538  1.146236e-06      1
420  1114059000    광희동    170   중구  ...     0.000016    2.670538  2.165113e-06      1
421  1111054000    삼청동    165  종로구  ...     0.000016    2.670538  2.101433e-06      1
422  1114060500   을지로동     44   중구  ...     0.000016    2.670538  3.735881e-07      1
423  1174069000  둔촌제1동     11  강동구  ...     0.000016    2.670538  9.339702e-08      1

[424 rows x 34 columns]

In [309]:
tf2 = [(max(win['new총시설수']+1)-(float(win['new총시설수'][i]))) for i in range(len(win))]
idf2 = np.log(len(win.행정동.unique()) / (1+cnt))
tfidf2 = [x*idf2 for x in tf2]
win['new센터tfidf'] = tfidf2
win['last수요지수'] = win['개선된돌봄교실이용비율'] * win['행정동별0514세/전체0514세'] *win['new센터tfidf']/win['학원tfidf']

In [310]:
win['last수요지수'] = win['개선된돌봄교실이용비율'] * win['행정동별0514세/전체0514세'] *win['new센터tfidf']/win['학원tfidf']

In [281]:
win[['행정동','시군구명','총시설수','수요지수','re수요지수','last수요지수','총학원수']].sort_values(by='re수요지수',ascending=False).head(10)

        행정동 시군구명  총시설수      수요지수    re수요지수  last수요지수  총학원수
324     오륜동  송파구   4.0  0.000061  0.000129  0.000129   8.0
25     월계3동  노원구  12.0  0.000249  0.000125  0.000124  17.0
309    가락1동  송파구   6.0  0.000091  0.000124  0.000124  10.0
316     내곡동  서초구   7.0  0.000109  0.000123  0.000123  12.0
97    도봉제1동  도봉구  10.0  0.000179  0.000122  0.000122   7.0
19     일원본동  강남구  11.0  0.000205  0.000120  0.000119  24.0
41   신대방제2동  동작구  12.0  0.000234  0.000117  0.000117  14.0
18     신월3동  양천구  11.0  0.000195  0.000114  0.000114  11.0
290     번2동  강북구   1.0  0.000019  0.000112  0.000112   0.0
127     중림동   중구   6.0  0.000082  0.000111  0.000111   5.0

In [282]:
pt = np.percentile(win[['last수요지수']],[i*10 for i in range(1,10)]).tolist()
len(pt)
# df2[df2['percentile'] == '10']
win['perc_'] = 0
win.loc[(win['last수요지수'] <= pt[0]),'perc_'] = '1'
win.loc[(win['last수요지수'] > pt[0]) & (win['last수요지수'] <= pt[1]),'perc_'] = '2'
win.loc[(win['last수요지수'] > pt[1]) & (win['last수요지수'] <= pt[2]),'perc_'] = '3'
win.loc[(win['last수요지수'] > pt[2]) & (win['last수요지수'] <= pt[3]),'perc_'] = '4'
win.loc[(win['last수요지수'] > pt[3]) & (win['last수요지수'] <= pt[4]),'perc_'] = '5'
win.loc[(win['last수요지수'] > pt[4]) & (win['last수요지수'] <= pt[5]),'perc_'] = '6'
win.loc[(win['last수요지수'] > pt[5]) & (win['last수요지수'] <= pt[6]),'perc_'] = '7'
win.loc[(win['last수요지수'] > pt[6]) & (win['last수요지수'] <= pt[7]),'perc_'] = '8'
win.loc[(win['last수요지수'] > pt[7]) & (win['last수요지수'] <= pt[8]),'perc_'] = '9'
win.loc[(win['last수요지수'] > pt[8]),'perc_'] = '10'

## 바뀐 센터 tfidf 적용


- 400개 동에 키움센터를 추가했을 때 , 지수의 감소여부 확인
- last수요지수(추가전) : 0.000186
- 400수요지수(추가전) : 0.000171

In [288]:
# win['last수요지수'] = win['정원 및 이용비율(fix)'] * win['행정동별0514세/전체0514세'] *win['new센터tfidf']/win['학원tfidf']
make = win[['행정동','시군구명','총시설수','수요지수','re수요지수','last수요지수','총학원수','percentile','percentile_','perc_']].sort_values(by='re수요지수',ascending=False)[:400]

# 오륜동	송파구	4.0	0.000061	0.000258	8.0
# 25	월계3동	노원구	12.0	0.000249	0.000249	17.0
# 309	가락1동	송파구	6.0	0.000091	0.000248	10.0
# 316	내곡동	서초구	7.0	0.000109	0.000246	12.0
# 97	도봉제1동	도봉구	10.0	0.000179	0.000244	7.0
# 19	일원본동	강남구	11.0	0.000205	0.000239	24.0
# 41	신대방제2동	동작구	12.0	0.000234	0.000234	14.0
# 18	신월3동	양천구	11.0	0.000195	0.000228	11.0
# 290	번2동	강북구	1.0	0.000019	0.000225	0.0
# 127	중림동

In [284]:
win[win['행정동']=='광장동']

          행정동코드  행정동  0514세 시군구명  ...  개선된돌봄교실이용비율  new센터tfidf  last수요지수  perc_
265  1121581000  광장동   5471  광진구  ...     0.005568    0.293759  0.000093     10

[1 rows x 34 columns]

In [215]:
# tf = [max(suyo['new총시설수']+1)-(float(suyo['new총시설수'][i])) for i in range(len(suyo))]
# idf = np.log(len(suyo.행정동.unique()) / (1+cnt))
# tfidf = [x*idf for x in tf]
# suyo['센터수정tfidf'] = tfidf

In [216]:
suyo

          행정동코드    행정동  0514세  ...      last수요지수  percentile_   센터수정tfidf
0    1165065100   양재1동   5145  ...  2.911910e-05            2    6.047372
1    1153078000  오류제2동   4507  ...  7.399572e-05            6   30.236861
2    1150063000  방화제1동   4970  ...  9.837376e-05            8   54.426350
3    1138069000    진관동   7384  ...  5.887938e-05            5   12.094744
4    1138062500    역촌동   3381  ...  1.043019e-04            8   84.663211
..          ...    ...    ...  ...           ...          ...         ...
419  1114057000     필동    180  ...  5.739099e-07            1  151.184304
420  1114059000    광희동    170  ...  1.084052e-06            1  151.184304
421  1111054000    삼청동    165  ...  1.052168e-06            1  151.184304
422  1114060500   을지로동     44  ...  1.870521e-07            1  151.184304
423  1174069000  둔촌제1동     11  ...  4.676303e-08            1  151.184304

[424 rows x 45 columns]

In [291]:
type(list(make['행정동']))

list

In [300]:
update = list(make['행정동'])
up = []
for i in range(len(win)):
  if win['행정동'][i] in update:
    up.append(1)
  else:up.append(0)

ppl=[]
for i in range(len(suyo)):
  if win['행정동'][i] in update:
    ppl.append(28)   # 28명으로 반영(서울시 돌봄키움센터정원)
  else:ppl.append(0)
win['추가센터400'],win['추가인원400'] = up,ppl

In [301]:
win['400총정원'] = win['총정원'] +win['추가인원400']
win['400총시설수'] = win['총시설수'] +win['추가센터400']

In [302]:
win['400돌봄교실이용비율'] = [(x+1)/sum(win['400총정원']) for x in win['400총정원']]

In [304]:
cnt = 0
for i in range(len(win['400총시설수'])):
    if win['400총시설수'][i] != 0:
        cnt += 1
cnt

400

In [307]:
tf4 = [(max(win['400총시설수']+1)-(float(win['400총시설수'][i]))) for i in range(len(win))]
idf4 = np.log(len(win.행정동.unique()) / (1+cnt))
tfidf4 = [x*idf2 for x in tf4]
win['400센터tfidf'] = tfidf4
win['400수요지수'] = win['400돌봄교실이용비율'] * win['행정동별0514세/전체0514세'] *win['400센터tfidf']/win['학원tfidf']

In [311]:
win[win['행정동']=='광장동']

          행정동코드  행정동  0514세 시군구명  ...  400총시설수  400돌봄교실이용비율  400센터tfidf   400수요지수
265  1121581000  광장동   5471  광진구  ...     14.0     0.004708    0.640929  0.000171

[1 rows x 41 columns]

### new 수요지수 제발 마지막 !

In [171]:
suyo.columns

Index(['행정동코드', '행정동', '0514세', '시군구명', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '키움센터_개수', '초등돌봄교실_이용인원', '초등돌봄교실_교실개수', '지역아동센터_정원', '지역아동센터_개수',
       '방과후아카데미_정원', '방과후아카데미_개수', '총시설수', 'tfidf', '돌봄교실이용비율', 'tfidf*이용비율',
       '행정동별0514세/전체0514세', 'tfidf*이용비율*인구비율', '정원 및 이용비율',
       'tfidf*정원 및 이용비율*인구비율', '예술학원', '보습학원개수', '총학원수', '학원tfidf', '총정원',
       '정원 및 이용비율(fix)', '수요지수', '수요지수_mmscaler', 'percentile', '추가센터', '추가인원',
       'new총정원', 'new총시설수', '개선된키움센터tfidf', '개선된돌봄교실이용비율'],
      dtype='object')

In [186]:
suyo['new수요지수'] = (suyo['개선된키움센터tfidf'] * suyo['행정동별0514세/전체0514세'] * suyo['개선된돌봄교실이용비율'])/suyo['학원tfidf']
suyo['new키움수요지수'] = (suyo['키움센터tfidf'] * suyo['행정동별0514세/전체0514세'] * suyo['개선된돌봄교실이용비율'])/suyo['학원tfidf']

In [209]:
suyo['last수요지수'] = (suyo['new센터tfidf'] * suyo['행정동별0514세/전체0514세'] * suyo['정원 및 이용비율(fix)'])/suyo['학원tfidf']

In [210]:
pt = np.percentile(suyo[['last수요지수']],[i*10 for i in range(1,10)]).tolist()
len(pt)
# df2[df2['percentile'] == '10']

9

In [211]:
suyo['percentile_'] = 0
suyo.loc[(suyo['last수요지수'] <= pt[0]),'percentile_'] = '1'
suyo.loc[(suyo['last수요지수'] > pt[0]) & (suyo['last수요지수'] <= pt[1]),'percentile_'] = '2'
suyo.loc[(suyo['last수요지수'] > pt[1]) & (suyo['last수요지수'] <= pt[2]),'percentile_'] = '3'
suyo.loc[(suyo['last수요지수'] > pt[2]) & (suyo['last수요지수'] <= pt[3]),'percentile_'] = '4'
suyo.loc[(suyo['last수요지수'] > pt[3]) & (suyo['last수요지수'] <= pt[4]),'percentile_'] = '5'
suyo.loc[(suyo['last수요지수'] > pt[4]) & (suyo['last수요지수'] <= pt[5]),'percentile_'] = '6'
suyo.loc[(suyo['last수요지수'] > pt[5]) & (suyo['last수요지수'] <= pt[6]),'percentile_'] = '7'
suyo.loc[(suyo['last수요지수'] > pt[6]) & (suyo['last수요지수'] <= pt[7]),'percentile_'] = '8'
suyo.loc[(suyo['last수요지수'] > pt[7]) & (suyo['last수요지수'] <= pt[8]),'percentile_'] = '9'
suyo.loc[(suyo['last수요지수'] > pt[8]),'percentile_'] = '10'

In [ ]:
pt = np.percentile(suyo[['new키움수요지수']],[i*10 for i in range(1,10)]).tolist()
len(pt)
# df2[df2['percentile'] == '10']

In [212]:
# suyo[suyo['행정동']=='광장동']
# suyo[suyo['행정동']=='독산제1동']
suyo[suyo['행정동']=='화곡제1동']

         행정동코드    행정동  0514세 시군구명  ...  new키움수요지수  new센터tfidf  last수요지수  percentile_
42  1150054000  화곡제1동   2452  강서구  ...   0.000641     0.69434  0.000126            9

[1 rows x 44 columns]

In [206]:
suyo[['행정동','총시설수','수요지수','last수요지수','총학원수']].sort_values(by='last수요지수',ascending=False).head(10)

       행정동  총시설수      수요지수  last수요지수  총학원수
7      세곡동  23.0  0.000831  0.000831  41.0
3      진관동  23.0  0.000707  0.000707  64.0
0     양재1동  24.0  0.000728  0.000699  52.0
15   길음제1동  14.0  0.000282  0.000469  48.0
25    월계3동  12.0  0.000249  0.000460  17.0
41  신대방제2동  12.0  0.000234  0.000451  14.0
16     강일동  15.0  0.000273  0.000426  39.0
19    일원본동  11.0  0.000205  0.000410  24.0
18    신월3동  11.0  0.000195  0.000407  11.0
97   도봉제1동  10.0  0.000179  0.000390   7.0

In [195]:
suyo[['총시설수','수요지수','총학원수']].sort_values(by='수요지수',ascending=False).head(10)

    총시설수      수요지수  총학원수
7   23.0  0.000831  41.0
0   24.0  0.000728  52.0
3   23.0  0.000707  64.0
1   20.0  0.000311  70.0
15  14.0  0.000282  48.0
8   19.0  0.000281  44.0
16  15.0  0.000273  39.0
10  15.0  0.000251  30.0
25  12.0  0.000249  17.0
36  17.0  0.000240  29.0

## 격자별 개선 인프라 지수

In [135]:
re = pd.read_csv('/content/drive/My Drive/Colab Notebooks/결과_키움센터추가될좌표.csv')

In [ ]:
re.columns = ['gid','행정동','거리']

In [ ]:
all = pd.read_pickle('/content/drive/My Drive/Colab Notebooks/동3_인프라필요지수.pkl')
all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83 entries, 0 to 82
Data columns (total 36 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   gid          83 non-null     object
 1   행정동코드        83 non-null     int64
 2   행정동          83 non-null     object
 3   위도           83 non-null     float64
 4   경도           83 non-null     float64
 5   학원명          83 non-null     object
 6   학원개수         83 non-null     float64
 7   학원tfidf      83 non-null     float64
 8   시군구명         83 non-null     object
 9   학교명          83 non-null     object
 10  학교개수         83 non-null     int64
 11  초등학생_인구      83 non-null     float64
 12  30대_인구       83 non-null     float64
 13  40대_인구       83 non-null     float64
 14  전체_인구        83 non-null     float64
 15  geometry     83 non-null     geometry
 16  초등학생인구비율     83 non-null     float64
 17  키움센터         83 non-null     object
 18  키움센터_개수      83 non-null     float64
 19  키움센터_상시돌봄정원  83 non-null     float64
 20  키움센터_일시돌봄정원  83 non-null     float64
 21  초등돌봄교실       83 non-null     object
 22  초등돌봄교실_개수    83 non-null     int64
 23  초등돌봄교실_교실개수  83 non-null     float64
 24  초등돌봄교실_이용인원  83 non-null     float64
 25  지역아동센터       83 non-null     object
 26  지역아동센터_개수    83 non-null     float64
 27  지역아동센터_정원    83 non-null     float64
 28  방과후아카데미_개수   83 non-null     int64
 29  방과후아카데미_정원   83 non-null     int64
 30  총정원          83 non-null     float64
 31  총시설수         83 non-null     float64
 32  돌봄교실이용비율     83 non-null     float64
 33  센터tfidf      83 non-null     float64
 34  수요지수         83 non-null     float64
 35  percentile   83 non-null     object
dtypes: float64(21), geometry(1), int64(5), object(9)
memory usage: 24.0+ KB

In [ ]:
df = pd.merge(all,re,how='left',on=['gid'])
df.fillna('x',inplace=True)

In [ ]:
add_list = []
for i in range(len(df)):
  if df['거리'][i]=='x':
    add_list.append(0)
  else :
    add_list.append(1)
df['추가키움'] = add_list
df[['거리','추가키움']].head(20)

         거리  추가키움
0   249.499     1
1   353.583     1
2   559.776     1
3   501.114     1
4   250.557     1
5         0     1
6   250.557     1
7   501.113     1
8   791.983     1
9   559.777     1
10  353.584     1
11    249.5     1
12  353.605     1
13        x     0
14  707.168     1
15  558.359     1
16        x     0
17  707.218     1
18  558.391     1
19  499.004     1

In [ ]:
df['추가키움'] = df['추가키움'].astype(str)

In [ ]:
with open('/content/drive/My Drive/수요지수_최종1012 (2).pkl', 'rb') as f:  
  suyo = pickle.load(f)

In [ ]:
# 서울시 키움센터 정원 평균값
(sum(suyo['키움센터_상시돌봄정원'])+sum(suyo['키움센터_일시돌봄정원']))/sum(suyo['키움센터_개수'])
# 28명

28.65934065934066

In [158]:
# 서울시 키움센터 총정원
sum(suyo['총정원']) + 28*3

60886.0

In [ ]:
a = df[df['행정동_x']=='화곡제1동']
b = df[df['행정동_x']=='독산제1동']
c = df[df['행정동_x']=='광장동']
b.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27 entries, 17 to 43
Data columns (total 39 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   gid          27 non-null     object
 1   행정동코드        27 non-null     int64
 2   행정동_x        27 non-null     object
 3   위도           27 non-null     float64
 4   경도           27 non-null     float64
 5   학원명          27 non-null     object
 6   학원개수         27 non-null     float64
 7   학원tfidf      27 non-null     float64
 8   시군구명         27 non-null     object
 9   학교명          27 non-null     object
 10  학교개수         27 non-null     int64
 11  초등학생_인구      27 non-null     float64
 12  30대_인구       27 non-null     float64
 13  40대_인구       27 non-null     float64
 14  전체_인구        27 non-null     float64
 15  geometry     27 non-null     geometry
 16  초등학생인구비율     27 non-null     float64
 17  키움센터         27 non-null     object
 18  키움센터_개수      27 non-null     float64
 19  키움센터_상시돌봄정원  27 non-null     float64
 20  키움센터_일시돌봄정원  27 non-null     float64
 21  초등돌봄교실       27 non-null     object
 22  초등돌봄교실_개수    27 non-null     int64
 23  초등돌봄교실_교실개수  27 non-null     float64
 24  초등돌봄교실_이용인원  27 non-null     float64
 25  지역아동센터       27 non-null     object
 26  지역아동센터_개수    27 non-null     float64
 27  지역아동센터_정원    27 non-null     float64
 28  방과후아카데미_개수   27 non-null     int64
 29  방과후아카데미_정원   27 non-null     int64
 30  총정원          27 non-null     float64
 31  총시설수         27 non-null     float64
 32  돌봄교실이용비율     27 non-null     float64
 33  센터tfidf      27 non-null     float64
 34  수요지수         27 non-null     float64
 35  percentile   27 non-null     object
 36  행정동_y        27 non-null     object
 37  거리           27 non-null     object
 38  추가키움         27 non-null     object
dtypes: float64(21), geometry(1), int64(5), object(12)
memory usage: 8.4+ KB

In [ ]:
add_1 = []
for i in range(len(a)):
  if a['추가키움'][i]=='1':
    add_1.append(28)
  else :
    add_1.append(0)
a['추가정원'] = add_1

In [ ]:
add_2 = []
for i in b['거리']:
  if i =='x':
    add_2.append(0)
  else:
    add_2.append(28)

b['추가정원'] = add_2
# add_2

In [ ]:
add_3 = []
for i in c['거리']:
  if i =='x':
    add_3.append(0)
  else:
    add_3.append(28)

c['추가정원'] = add_3
# add_2

### 화곡 제1동

In [ ]:
a['추가키움'] = a['추가키움'].astype(int)
a['개선된총정원'] = a['총정원']+a['추가정원']
a['개선된총시설수'] = a['총시설수']+a['추가키움']
a['개선된돌봄교실이용비율'] = [(x+1)/(sum(suyo['총정원']) + 20*3) for x in a['개선된총정원']]

In [ ]:
a['돌봄교실이용비율'] = [x/sum(a['개선된총정원']) for x in a['개선된총정원']]

tf_a = a['개선된총시설수'] + 1
idf_a = (len(a.gid.unique()) / (len(a)+1))
tfidf_a = tf_a*idf_a
a['센터tfidf_new']= tfidf_a
# tfidf_center
a.columns

Index(['gid', '행정동코드', '행정동_x', '위도', '경도', '학원명', '학원개수', '학원tfidf', '시군구명',
       '학교명', '학교개수', '초등학생_인구', '30대_인구', '40대_인구', '전체_인구', 'geometry',
       '초등학생인구비율', '키움센터', '키움센터_개수', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원', '초등돌봄교실',
       '초등돌봄교실_개수', '초등돌봄교실_교실개수', '초등돌봄교실_이용인원', '지역아동센터', '지역아동센터_개수',
       '지역아동센터_정원', '방과후아카데미_개수', '방과후아카데미_정원', '총정원', '총시설수', '돌봄교실이용비율',
       '센터tfidf', '수요지수', 'percentile', '행정동_y', '거리', '추가키움', '추가정원',
       '개선된총정원', '개선된총시설수', '센터tfidf_new', '개선된돌봄교실이용비율'],
      dtype='object')

In [ ]:
a['new_인프라지수'] = (a['센터tfidf_new']* a['개선된돌봄교실이용비율']* a['초등학생인구비율']) /a['학원tfidf']

In [ ]:
a

           gid       행정동코드  행정동_x  ...  센터tfidf_new  개선된돌봄교실이용비율 new_인프라지수
0   다사41ab48ba  1150054000  화곡제1동  ...    16.055556     0.009579  0.000442
1   다사41ab48bb  1150054000  화곡제1동  ...    14.166667     0.008938  0.000160
2   다사41ab49aa  1150054000  화곡제1동  ...    12.277778     0.008314  0.000172
3   다사41ba48aa  1150054000  화곡제1동  ...    13.222222     0.007690  0.000168
4   다사41ba48ab  1150054000  화곡제1동  ...    13.222222     0.007624  0.000172
5   다사41ba48ba  1150054000  화곡제1동  ...    12.277778     0.007197  0.000262
6   다사41ba48bb  1150054000  화곡제1동  ...    13.222222     0.008495  0.000176
7   다사41ba49aa  1150054000  화곡제1동  ...    11.333333     0.008725  0.000135
8   다사41bb47bb  1150054000  화곡제1동  ...    17.000000     0.009760  0.000167
9   다사41bb48aa  1150054000  화곡제1동  ...    14.166667     0.007410  0.000185
10  다사41bb48ab  1150054000  화곡제1동  ...    11.333333     0.006999  0.000146
11  다사41bb48ba  1150054000  화곡제1동  ...    10.388889     0.007394  0.000181
12  다사41bb48bb  1150054000  화곡제1동  ...    15.111111     0.010499  0.000156
13  다사42aa47bb  1150054000  화곡제1동  ...    15.111111     0.011321  0.000139
14  다사42aa48aa  1150054000  화곡제1동  ...    14.166667     0.010335  0.000194
15  다사42aa48ab  1150054000  화곡제1동  ...    12.277778     0.009037  0.000056
16  다사42ab47bb  1150054000  화곡제1동  ...    12.277778     0.009398  0.000000

[17 rows x 45 columns]

In [ ]:
b.columns

Index(['gid', '행정동코드', '행정동_x', '위도', '경도', '학원명', '학원개수', '학원tfidf', '시군구명',
       '학교명', '학교개수', '초등학생_인구', '30대_인구', '40대_인구', '전체_인구', 'geometry',
       '초등학생인구비율', '키움센터', '키움센터_개수', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원', '초등돌봄교실',
       '초등돌봄교실_개수', '초등돌봄교실_교실개수', '초등돌봄교실_이용인원', '지역아동센터', '지역아동센터_개수',
       '지역아동센터_정원', '방과후아카데미_개수', '방과후아카데미_정원', '총정원', '총시설수', '돌봄교실이용비율',
       '센터tfidf', '수요지수', 'percentile', '행정동_y', '거리', '추가키움', '추가정원',
       '개선된총정원', '개선된총시설수', '센터tfidf_new', '개선된돌봄교실이용비율'],
      dtype='object')

### 독산1

In [ ]:
b['추가키움'] = b['추가키움'].astype(int)
b['개선된총정원'] = b['총정원']+b['추가정원']
b['개선된총시설수'] = b['총시설수']+b['추가키움']
b['개선된돌봄교실이용비율'] = [(x+1)/(sum(suyo['총정원']) + 20*3) for x in b['개선된총정원']]

tf_b = b['개선된총시설수'] + 1
idf_b = (len(b.gid.unique()) / (len(b)+1))
tfidf_b = tf_b*idf_b
b['센터tfidf_new']= tfidf_b
# tfidf_center
b['new_인프라지수'] = (b['센터tfidf_new']* b['개선된돌봄교실이용비율']* b['초등학생인구비율']) /b['학원tfidf']

### 광장동

In [ ]:
c['추가키움'] = c['추가키움'].astype(int)
c['개선된총정원'] = c['총정원']+c['추가정원']
c['개선된총시설수'] = c['총시설수']+c['추가키움']
c['개선된돌봄교실이용비율'] = [(x+1)/(sum(suyo['총정원']) + 20*3) for x in c['개선된총정원']]

tf_c = c['개선된총시설수'] + 1
idf_c = (len(c.gid.unique()) / (len(c)+1))
tfidf_c = tf_c*idf_c
c['센터tfidf_new']= tfidf_c
# tfidf_center
c['new_인프라지수'] = (c['센터tfidf_new']* c['개선된돌봄교실이용비율']* c['초등학생인구비율']) /c['학원tfidf']

In [ ]:
a.shape,b.shape,c.shape

((17, 44), (27, 44), (39, 44))

In [ ]:
lst = [a,b,c,]
new_index = pd.concat(lst)
len(new_index)

(83, 54)

In [ ]:
new_index.to_pickle('동3개_개선인프라지수.pickle')

## 기존 동3 인프라 지수 구하기

In [ ]:
with open('/content/drive/My Drive/동3개_초등학교881m_학원정보.pkl', 'rb') as f:  
  aca = pickle.load(f)

  # /content/drive/My Drive/동3개_초등학교881m_돌봄시설정보.pkl

In [ ]:
with open('/content/drive/My Drive/동3개_초등학교881m_인구.pkl', 'rb') as f:  
  pop = pickle.load(f)

In [ ]:
with open('/content/drive/My Drive/동3개_초등학교881m_돌봄시설정보.pkl', 'rb') as f:  
  dol = pickle.load(f)
 
# /content/drive/My Drive/금천구_초등학교881m_돌봄시설정보.pkl

In [ ]:
aca.info()
aca.fillna(0,inplace=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   gid     83 non-null     object
 1   행정동코드   83 non-null     int64
 2   행정동     83 non-null     object
 3   위도      83 non-null     float64
 4   경도      83 non-null     float64
 5   학원명     82 non-null     object
 6   학원개수    82 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 5.2+ KB

In [ ]:
aca

           gid  ...  학원개수
0   다사41ab48ba  ...  35.0
1   다사41ab48bb  ...  41.0
2   다사41ab49aa  ...  50.0
3   다사41ba48aa  ...  33.0
4   다사41ba48ab  ...  30.0
..         ...  ...   ...
78  다사65ab50ab  ...   3.0
79  다사65ab50ba  ...   2.0
80  다사65ab50bb  ...   1.0
81  다사65ba49bb  ...   3.0
82  다사65ba50aa  ...   3.0

[83 rows x 7 columns]

In [ ]:
a = aca[aca['행정동']=='화곡제1동']
b = aca[aca['행정동']=='독산제1동']
c = aca[aca['행정동']=='광장동']

In [ ]:
# aca.행정동.unique()
a

           gid  ...  학원개수
0   다사41ab48ba  ...  35.0
1   다사41ab48bb  ...  41.0
2   다사41ab49aa  ...  50.0
3   다사41ba48aa  ...  33.0
4   다사41ba48ab  ...  30.0
5   다사41ba48ba  ...  39.0
6   다사41ba48bb  ...  44.0
7   다사41ba49aa  ...  55.0
8   다사41bb47bb  ...  51.0
9   다사41bb48aa  ...  39.0
10  다사41bb48ab  ...  34.0
11  다사41bb48ba  ...  36.0
12  다사41bb48bb  ...  48.0
13  다사42aa47bb  ...  50.0
14  다사42aa48aa  ...  44.0
15  다사42aa48ab  ...  35.0
16  다사42ab47bb  ...  39.0

[17 rows x 7 columns]

In [ ]:
sum(a['학원개수']),sum(b['학원개수']),sum(c['학원개수'])

(703.0, 455.0, 902.0)

In [ ]:
cnt_a = 0
for i in range(len(a['학원개수'])):
    if aca['학원개수'][i] != 0:
        cnt_a += 1
cnt_a ,len(a)

(17, 17)

In [ ]:
cnt_b = 0
for i in range(len(b['학원개수'])):
    if aca['학원개수'][i] != 0:
        cnt_b += 1
cnt_b,len(b)

(27, 27)

In [ ]:
c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39 entries, 44 to 82
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   gid      39 non-null     object
 1   행정동코드    39 non-null     int64
 2   행정동      39 non-null     object
 3   위도       39 non-null     float64
 4   경도       39 non-null     float64
 5   학원명      39 non-null     object
 6   학원개수     39 non-null     float64
 7   학원tfidf  39 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 2.7+ KB

In [ ]:
# cnt_c = 0
# for i in range(len(c['학원개수'])):
#     if aca['학원개수'][i] != 0:
#         cnt_c += 1
cnt_c = len(c) -1

In [ ]:
tf_aca = [(float(a['학원개수'][i] + 1)) for i in range(len(a))]
idf_aca = ((len(a.gid.unique())) / (cnt_a+1))
tfidf_aca = [x*idf_aca for x in tf_aca]
a['학원tfidf'] = tfidf_aca 
# idf_aca
# tfidf_aca
a

           gid       행정동코드  ...  학원개수    학원tfidf
0   다사41ab48ba  1150054000  ...  35.0  34.000000
1   다사41ab48bb  1150054000  ...  41.0  39.666667
2   다사41ab49aa  1150054000  ...  50.0  48.166667
3   다사41ba48aa  1150054000  ...  33.0  32.111111
4   다사41ba48ab  1150054000  ...  30.0  29.277778
5   다사41ba48ba  1150054000  ...  39.0  37.777778
6   다사41ba48bb  1150054000  ...  44.0  42.500000
7   다사41ba49aa  1150054000  ...  55.0  52.888889
8   다사41bb47bb  1150054000  ...  51.0  49.111111
9   다사41bb48aa  1150054000  ...  39.0  37.777778
10  다사41bb48ab  1150054000  ...  34.0  33.055556
11  다사41bb48ba  1150054000  ...  36.0  34.944444
12  다사41bb48bb  1150054000  ...  48.0  46.277778
13  다사42aa47bb  1150054000  ...  50.0  48.166667
14  다사42aa48aa  1150054000  ...  44.0  42.500000
15  다사42aa48ab  1150054000  ...  35.0  34.000000
16  다사42ab47bb  1150054000  ...  39.0  37.777778

[17 rows x 8 columns]

In [ ]:
tf_b = b['학원개수']+1
idf_aca_b = ((len(b.gid.unique())) / (cnt_b+1))
tfidf_aca_b = tf_b*idf_aca_b 
b['학원tfidf'] = tfidf_aca_b 
# tfidf_aca_b
# idf_aca_b
# tf_b
b

           gid       행정동코드  ...  학원개수    학원tfidf
17  다사45bb39bb  1154561000  ...   9.0   9.642857
18  다사45bb40aa  1154561000  ...  10.0  10.607143
19  다사45bb40ab  1154561000  ...  12.0  12.535714
20  다사46aa39ba  1154561000  ...  11.0  11.571429
21  다사46aa39bb  1154561000  ...  11.0  11.571429
22  다사46aa40aa  1154561000  ...  12.0  12.535714
23  다사46aa40ab  1154561000  ...  16.0  16.392857
24  다사46aa40ba  1154561000  ...  16.0  16.392857
25  다사46aa40bb  1154561000  ...  14.0  14.464286
26  다사46aa41aa  1154561000  ...  10.0  10.607143
27  다사46aa41ab  1154561000  ...   9.0   9.642857
28  다사46ab39ba  1154561000  ...  12.0  12.535714
29  다사46ab40aa  1154561000  ...  15.0  15.428571
30  다사46ab40ab  1154561000  ...  19.0  19.285714
31  다사46ab40ba  1154561000  ...  23.0  23.142857
32  다사46ab40bb  1154561000  ...  23.0  23.142857
33  다사46ab41aa  1154561000  ...  20.0  20.250000
34  다사46ab41ab  1154561000  ...  17.0  17.357143
35  다사46ba40aa  1154561000  ...  23.0  23.142857
36  다사46ba40ab  1154561000  ...  26.0  26.035714
37  다사46ba40ba  1154561000  ...  26.0  26.035714
38  다사46ba40bb  1154561000  ...  29.0  28.928571
39  다사46ba41aa  1154561000  ...  25.0  25.071429
40  다사46ba41ab  1154561000  ...  23.0  23.142857
41  다사46ba41ba  1154561000  ...  18.0  18.321429
42  다사46ba41bb  1154561000  ...  15.0  15.428571
43  다사46ba42aa  1154561000  ...  11.0  11.571429

[27 rows x 8 columns]

In [ ]:
tf_c = c['학원개수']+1
idf_aca_c = ((len(c.gid.unique())) / (cnt_c+1))
tfidf_aca_c = tf_c*idf_aca_c 
c['학원tfidf'] = tfidf_aca_c 
# tfidf_aca_b
# idf_aca_b
# tf_b
c

           gid       행정동코드  ...  학원개수  학원tfidf
44  다사64aa49ab  1121581000  ...  63.0     64.0
45  다사64ab49aa  1121581000  ...  54.0     55.0
46  다사64ab49ab  1121581000  ...  53.0     54.0
47  다사64ab49ba  1121581000  ...  60.0     61.0
48  다사64ba48bb  1121581000  ...  51.0     52.0
49  다사64ba49aa  1121581000  ...  51.0     52.0
50  다사64ba49ab  1121581000  ...  51.0     52.0
51  다사64ba49ba  1121581000  ...  55.0     56.0
52  다사64ba49bb  1121581000  ...  50.0     51.0
53  다사64ba50aa  1121581000  ...  13.0     14.0
54  다사64ba50ab  1121581000  ...   9.0     10.0
55  다사64bb48ba  1121581000  ...  33.0     34.0
56  다사64bb48bb  1121581000  ...  43.0     44.0
57  다사64bb49aa  1121581000  ...  50.0     51.0
58  다사64bb49ab  1121581000  ...  51.0     52.0
59  다사64bb49ba  1121581000  ...  47.0     48.0
60  다사64bb49bb  1121581000  ...  19.0     20.0
61  다사64bb50aa  1121581000  ...   7.0      8.0
62  다사64bb50ab  1121581000  ...   5.0      6.0
63  다사64bb50ba  1121581000  ...   5.0      6.0
64  다사65aa48bb  1121581000  ...  18.0     19.0
65  다사65aa49aa  1121581000  ...  25.0     26.0
66  다사65aa49ab  1121581000  ...  23.0     24.0
67  다사65aa49ba  1121581000  ...  13.0     14.0
68  다사65aa49bb  1121581000  ...   9.0     10.0
69  다사65aa50aa  1121581000  ...   3.0      4.0
70  다사65aa50ab  1121581000  ...   3.0      4.0
71  다사65aa50ba  1121581000  ...   2.0      3.0
72  다사65aa50bb  1121581000  ...   1.0      2.0
73  다사65aa51aa  1121581000  ...   0.0      1.0
74  다사65ab49ab  1121581000  ...   9.0     10.0
75  다사65ab49ba  1121581000  ...   6.0      7.0
76  다사65ab49bb  1121581000  ...   5.0      6.0
77  다사65ab50aa  1121581000  ...   3.0      4.0
78  다사65ab50ab  1121581000  ...   3.0      4.0
79  다사65ab50ba  1121581000  ...   2.0      3.0
80  다사65ab50bb  1121581000  ...   1.0      2.0
81  다사65ba49bb  1121581000  ...   3.0      4.0
82  다사65ba50aa  1121581000  ...   3.0      4.0

[39 rows x 8 columns]

In [ ]:
lst = [a,b,c]
academy_all = pd.concat(lst,axis=0)
academy_all

           gid       행정동코드  ...  학원개수    학원tfidf
0   다사41ab48ba  1150054000  ...  35.0  34.000000
1   다사41ab48bb  1150054000  ...  41.0  39.666667
2   다사41ab49aa  1150054000  ...  50.0  48.166667
3   다사41ba48aa  1150054000  ...  33.0  32.111111
4   다사41ba48ab  1150054000  ...  30.0  29.277778
..         ...         ...  ...   ...        ...
78  다사65ab50ab  1121581000  ...   3.0   4.000000
79  다사65ab50ba  1121581000  ...   2.0   3.000000
80  다사65ab50bb  1121581000  ...   1.0   2.000000
81  다사65ba49bb  1121581000  ...   3.0   4.000000
82  다사65ba50aa  1121581000  ...   3.0   4.000000

[83 rows x 8 columns]

In [ ]:
academy_all.행정동.unique()

array(['화곡제1동', '독산제1동', '광장동'], dtype=object)

In [ ]:
hwa = pop[pop['행정동']=='화곡제1동']
dok = pop[pop['행정동']=='독산제1동']
gwang = pop[pop['행정동']=='광장동']

In [ ]:
sum(hwa['초등학생_인구'])

1278.0

In [ ]:
dol.fillna(0,inplace=True)

In [ ]:
popcnt = 0
for i in range(len(pop['초등학생_인구'])):
    if pop['초등학생_인구'][i] != 0:
        popcnt += pop['초등학생_인구'][i]
popcnt

6178.0

In [ ]:
dol['총정원'] = dol['키움센터_상시돌봄정원']+dol['키움센터_일시돌봄정원']+dol['초등돌봄교실_이용인원']+dol['지역아동센터_정원']+dol['방과후아카데미_정원']
dol['총시설수'] = dol['키움센터_개수']+dol['초등돌봄교실_개수']+dol['지역아동센터_개수']+dol['방과후아카데미_개수']

In [ ]:
dol.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83 entries, 0 to 82
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   gid          83 non-null     object
 1   행정동코드        83 non-null     int64
 2   행정동          83 non-null     object
 3   위도           83 non-null     float64
 4   경도           83 non-null     float64
 5   키움센터         83 non-null     object
 6   키움센터_개수      83 non-null     float64
 7   키움센터_상시돌봄정원  83 non-null     float64
 8   키움센터_일시돌봄정원  83 non-null     float64
 9   초등돌봄교실       83 non-null     object
 10  초등돌봄교실_개수    83 non-null     int64
 11  초등돌봄교실_교실개수  83 non-null     float64
 12  초등돌봄교실_이용인원  83 non-null     float64
 13  지역아동센터       83 non-null     object
 14  지역아동센터_개수    83 non-null     float64
 15  지역아동센터_정원    83 non-null     float64
 16  방과후아카데미_개수   83 non-null     int64
 17  방과후아카데미_정원   83 non-null     int64
 18  총정원          83 non-null     float64
 19  총시설수         83 non-null     float64
dtypes: float64(11), int64(4), object(5)
memory usage: 13.6+ KB

In [ ]:
hwa = dol[dol['행정동']=='화곡제1동']
dok = dol[dol['행정동']=='독산제1동']
gwang = dol[dol['행정동']=='광장동']

In [ ]:
sum(hwa['총정원']),sum(dok['총정원']),sum(gwang['총정원'])

(8614.0, 11402.0, 10819.0)

In [ ]:
hwa['돌봄교실이용비율'] = [x/sum(hwa['총정원']) for x in hwa['총정원']]
dok['돌봄교실이용비율'] = [x/sum(dok['총정원']) for x in dok['총정원']]
gwang['돌봄교실이용비율'] = [x/sum(gwang['총정원']) for x in gwang['총정원']]
tf_hwa = hwa['총시설수'] + 1
idf_center = (len(hwa.gid.unique()) / (hwa_cnt+1))
tfidf_center =tf_hwa*idf_center
hwa['센터tfidf']= tfidf_center
# tfidf_center

In [ ]:
# gwang

In [ ]:
#  tf_center = [float(all['총학원수'][i]+1) / float(all['총학원수'].sum()) for i in range(len(all))]
#  idf = float(len(all.행정동코드.unique()) / (423))
#  tfidf = [x*idf for x in tf]

In [ ]:
hwa_cnt = len(hwa)
dok_cnt = len(dok)
gwang_cnt = len(gwang)

In [ ]:
tf_hwa = hwa['총시설수'] + 1
idf_center = (len(hwa.gid.unique()) / (hwa_cnt+1))
tfidf_center =tf_hwa*idf_center
hwa['센터tfidf']= tfidf_center
# tfidf_center

In [ ]:
tf_dok = dok['총시설수'] + 1
idf_dok = (len(dok.gid.unique()) / (dok_cnt+1))
tfidf_dok =tf_dok*idf_dok
dok['센터tfidf']= tfidf_dok

In [ ]:
tf_gwang = gwang['총시설수'] + 1
idf_gwang = (len(gwang.gid.unique()) / (gwang_cnt+1))
tfidf_gwang =tf_gwang*idf_gwang
gwang['센터tfidf']= tfidf_gwang

In [ ]:
dong = [hwa , dok, gwang]
dol_df = pd.concat(dong)
dol_df

           gid       행정동코드    행정동         위도  ...    총정원  총시설수  돌봄교실이용비율    센터tfidf
0   다사41ab48ba  1150054000  화곡제1동  37.535080  ...  554.0  15.0  0.064314  15.111111
1   다사41ab48bb  1150054000  화곡제1동  37.537333  ...  515.0  13.0  0.059786  13.222222
2   다사41ab49aa  1150054000  화곡제1동  37.539586  ...  477.0  11.0  0.055375  11.333333
3   다사41ba48aa  1150054000  화곡제1동  37.530589  ...  439.0  12.0  0.050964  12.277778
4   다사41ba48ab  1150054000  화곡제1동  37.532842  ...  435.0  12.0  0.050499  12.277778
..         ...         ...    ...        ...  ...    ...   ...       ...        ...
78  다사65ab50ab  1121581000    광장동  37.552067  ...  144.0   2.0  0.013310   2.925000
79  다사65ab50ba  1121581000    광장동  37.554320  ...  144.0   2.0  0.013310   2.925000
80  다사65ab50bb  1121581000    광장동  37.556574  ...   97.0   1.0  0.008966   1.950000
81  다사65ba49bb  1121581000    광장동  37.547570  ...   47.0   1.0  0.004344   1.950000
82  다사65ba50aa  1121581000    광장동  37.549823  ...   47.0   1.0  0.004344   1.950000

[83 rows x 22 columns]

In [ ]:
p1 = pop[pop['행정동']=='화곡제1동']
p2 = pop[pop['행정동']=='독산제1동']
p3 = pop[pop['행정동']=='광장동']
p1['초등학생인구비율'] = p1['초등학생_인구']/(sum(p1['초등학생_인구']))
p2['초등학생인구비율'] = p2['초등학생_인구']/(sum(p2['초등학생_인구']))
p3['초등학생인구비율'] = p3['초등학생_인구']/(sum(p3['초등학생_인구']))
pop_lst = [p1,p2,p3]
population = pd.concat(pop_lst)

In [ ]:
len(academy_all),len(dol_df),len(population)

(83, 83, 83)

In [ ]:
df1 = pd.merge(academy_all,population,on=['gid'])
df2 = pd.merge(df1,dol_df,on=['gid'])
df2.columns

Index(['gid', '행정동코드_x', '행정동_x', '위도_x', '경도_x', '학원명', '학원개수', '학원tfidf',
       '행정동코드_y', '시군구명', '행정동_y', '학교명', '학교개수', '초등학생_인구', '30대_인구',
       '40대_인구', '전체_인구', '경도_y', '위도_y', 'geometry', '초등학생인구비율', '행정동코드',
       '행정동', '위도', '경도', '키움센터', '키움센터_개수', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '초등돌봄교실', '초등돌봄교실_개수', '초등돌봄교실_교실개수', '초등돌봄교실_이용인원', '지역아동센터',
       '지역아동센터_개수', '지역아동센터_정원', '방과후아카데미_개수', '방과후아카데미_정원', '총정원', '총시설수',
       '돌봄교실이용비율', '센터tfidf'],
      dtype='object')

In [ ]:
df2 = df2[['gid', '행정동코드_x', '행정동_x', '위도_x', '경도_x', '학원명', '학원개수', '학원tfidf',
       '시군구명', '학교명', '학교개수', '초등학생_인구', '30대_인구',
       '40대_인구', '전체_인구', 'geometry', '초등학생인구비율','키움센터', '키움센터_개수', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '초등돌봄교실', '초등돌봄교실_개수', '초등돌봄교실_교실개수', '초등돌봄교실_이용인원', '지역아동센터',
       '지역아동센터_개수', '지역아동센터_정원', '방과후아카데미_개수', '방과후아카데미_정원', '총정원', '총시설수',
       '돌봄교실이용비율', '센터tfidf']]

In [ ]:
df2.columns =['gid', '행정동코드', '행정동', '위도', '경도', '학원명', '학원개수', '학원tfidf',
       '시군구명', '학교명', '학교개수', '초등학생_인구', '30대_인구',
       '40대_인구', '전체_인구', 'geometry', '초등학생인구비율','키움센터', '키움센터_개수', '키움센터_상시돌봄정원', '키움센터_일시돌봄정원',
       '초등돌봄교실', '초등돌봄교실_개수', '초등돌봄교실_교실개수', '초등돌봄교실_이용인원', '지역아동센터',
       '지역아동센터_개수', '지역아동센터_정원', '방과후아카데미_개수', '방과후아카데미_정원', '총정원', '총시설수',
       '돌봄교실이용비율', '센터tfidf']

In [ ]:
# ratio =  [(i+1) / sum(df2['초등학생_인구']) for i in df2['초등학생_인구']]
# df2['인구비율'] = ratio

In [ ]:
df2['수요지수'] = df2['센터tfidf'] * df2['초등학생인구비율']* df2['돌봄교실이용비율'] / df2['학원tfidf']

In [ ]:
df2.행정동.unique()

array(['화곡제1동', '독산제1동', '광장동'], dtype=object)

In [ ]:
d1 = df2[df2['행정동']=='화곡제1동']
d2 = df2[df2['행정동']=='독산제1동']
d3 = df2[df2['행정동']== '광장동']

In [ ]:
pt1 = np.percentile(d1[['수요지수']],[i*10 for i in range(1,10)]).tolist()
pt2 = np.percentile(d2[['수요지수']],[i*10 for i in range(1,10)]).tolist()
pt3 = np.percentile(d3[['수요지수']],[i*10 for i in range(1,10)]).tolist()

len(pt1)
# df2[df2['percentile'] == '10']

9

In [ ]:
d1['percentile'] = 0
d1.loc[(d1['수요지수'] <= pt1[0]),'percentile'] = '1'
d1.loc[(d1['수요지수'] > pt1[0]) & (d1['수요지수'] <= pt1[1]),'percentile'] = '2'
d1.loc[(d1['수요지수'] > pt1[1]) & (d1['수요지수'] <= pt1[2]),'percentile'] = '3'
d1.loc[(d1['수요지수'] > pt1[2]) & (d1['수요지수'] <= pt1[3]),'percentile'] = '4'
d1.loc[(d1['수요지수'] > pt1[3]) & (d1['수요지수'] <= pt1[4]),'percentile'] = '5'
d1.loc[(d1['수요지수'] > pt1[4]) & (d1['수요지수'] <= pt1[5]),'percentile'] = '6'
d1.loc[(d1['수요지수'] > pt1[5]) & (d1['수요지수'] <= pt1[6]),'percentile'] = '7'
d1.loc[(d1['수요지수'] > pt1[6]) & (d1['수요지수'] <= pt1[7]),'percentile'] = '8'
d1.loc[(d1['수요지수'] > pt1[7]) & (d1['수요지수'] <= pt1[8]),'percentile'] = '9'
d1.loc[(d1['수요지수'] > pt1[8]),'percentile'] = '10'
d1.shape

(17, 36)

In [ ]:
d2['percentile'] = 0
d2.loc[(d2['수요지수'] > pt2[0]) & (d2['수요지수'] <= pt2[1]),'percentile'] = '2'
d2.loc[(d2['수요지수'] > pt2[1]) & (d2['수요지수'] <= pt2[2]),'percentile'] = '3'
d2.loc[(d2['수요지수'] > pt2[2]) & (d2['수요지수'] <= pt2[3]),'percentile'] = '4'
d2.loc[(d2['수요지수'] > pt2[3]) & (d2['수요지수'] <= pt2[4]),'percentile'] = '5'
d2.loc[(d2['수요지수'] > pt2[4]) & (d2['수요지수'] <= pt2[5]),'percentile'] = '6'
d2.loc[(d2['수요지수'] > pt2[5]) & (d2['수요지수'] <= pt2[6]),'percentile'] = '7'
d2.loc[(d2['수요지수'] > pt2[6]) & (d2['수요지수'] <= pt2[7]),'percentile'] = '8'
d2.loc[(d2['수요지수'] > pt2[7]) & (d2['수요지수'] <= pt2[8]),'percentile'] = '9'
d2.loc[(d2['수요지수'] > pt2[8]),'percentile'] = '10'
d2.shape

(27, 36)

In [ ]:
d3['percentile'] = 0
d3.loc[(d3['수요지수'] > pt3[0]) & (d3['수요지수'] <= pt3[1]),'percentile'] = '2'
d3.loc[(d3['수요지수'] > pt3[1]) & (d3['수요지수'] <= pt3[2]),'percentile'] = '3'
d3.loc[(d3['수요지수'] > pt3[2]) & (d3['수요지수'] <= pt3[3]),'percentile'] = '4'
d3.loc[(d3['수요지수'] > pt3[3]) & (d3['수요지수'] <= pt3[4]),'percentile'] = '5'
d3.loc[(d3['수요지수'] > pt3[4]) & (d3['수요지수'] <= pt3[5]),'percentile'] = '6'
d3.loc[(d3['수요지수'] > pt3[5]) & (d3['수요지수'] <= pt3[6]),'percentile'] = '7'
d3.loc[(d3['수요지수'] > pt3[6]) & (d3['수요지수'] <= pt3[7]),'percentile'] = '8'
d3.loc[(d3['수요지수'] > pt3[7]) & (d3['수요지수'] <= pt3[8]),'percentile'] = '9'
d3.loc[(d3['수요지수'] > pt3[8]),'percentile'] = '10'
d3.shape

(39, 36)

In [ ]:
len(d2[d2['percentile'] == '10']),len(d2[d2['percentile'] == '9']),len(d2[d2['percentile'] == '8']),len(d2[d2['percentile'] == '7'])

(3, 3, 2, 3)

In [ ]:
len(d1[d1['percentile'] == '10']),len(d1[d1['percentile'] == '9']),len(d1[d1['percentile'] == '8']),len(d1[d1['percentile'] == '7']),len(d1[d1['percentile'] == '9'])

(2, 2, 1, 2, 2)

In [ ]:
d1
# df2['percentile'] = df2['percentile'].astype(int)

           gid       행정동코드    행정동  ...    센터tfidf      수요지수 percentile
0   다사41ab48ba  1150054000  화곡제1동  ...  15.111111  0.002796         10
1   다사41ab48bb  1150054000  화곡제1동  ...  13.222222  0.000998          4
2   다사41ab49aa  1150054000  화곡제1동  ...  11.333333  0.001060          6
3   다사41ba48aa  1150054000  화곡제1동  ...  12.277778  0.001037          5
4   다사41ba48ab  1150054000  화곡제1동  ...  12.277778  0.001061          7
5   다사41ba48ba  1150054000  화곡제1동  ...  11.333333  0.001594         10
6   다사41ba48bb  1150054000  화곡제1동  ...  12.277778  0.001089          8
7   다사41ba49aa  1150054000  화곡제1동  ...  10.388889  0.000824          2
8   다사41bb47bb  1150054000  화곡제1동  ...  16.055556  0.001057          5
9   다사41bb48aa  1150054000  화곡제1동  ...  13.222222  0.001140          9
10  다사41bb48ab  1150054000  화곡제1동  ...  10.388889  0.000884          2
11  다사41bb48ba  1150054000  화곡제1동  ...   9.444444  0.001085          7
12  다사41bb48bb  1150054000  화곡제1동  ...  14.166667  0.000984          4
13  다사42aa47bb  1150054000  화곡제1동  ...  15.111111  0.000980          3
14  다사42aa48aa  1150054000  화곡제1동  ...  13.222222  0.001221          9
15  다사42aa48ab  1150054000  화곡제1동  ...  11.333333  0.000347          1
16  다사42ab47bb  1150054000  화곡제1동  ...  12.277778  0.000000          1

[17 rows x 36 columns]

In [ ]:
df_lst = [d1,d2,d3]
df_all = pd.concat(df_lst)
len(df_all)

83

In [ ]:
df_all

           gid       행정동코드    행정동  ...    센터tfidf      수요지수 percentile
0   다사41ab48ba  1150054000  화곡제1동  ...  15.111111  0.002796         10
1   다사41ab48bb  1150054000  화곡제1동  ...  13.222222  0.000998          4
2   다사41ab49aa  1150054000  화곡제1동  ...  11.333333  0.001060          6
3   다사41ba48aa  1150054000  화곡제1동  ...  12.277778  0.001037          5
4   다사41ba48ab  1150054000  화곡제1동  ...  12.277778  0.001061          7
..         ...         ...    ...  ...        ...       ...        ...
78  다사65ab50ab  1121581000    광장동  ...   2.925000  0.000040          7
79  다사65ab50ba  1121581000    광장동  ...   2.925000  0.000000          0
80  다사65ab50bb  1121581000    광장동  ...   1.950000  0.000000          0
81  다사65ba49bb  1121581000    광장동  ...   1.950000  0.000000          0
82  다사65ba50aa  1121581000    광장동  ...   1.950000  0.000008          6

[83 rows x 36 columns]

In [ ]:
df_all.to_pickle('동3_인프라필요지수.pkl')